{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ff-proxy.fullname" . }}-redis-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ff-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
