{{- if .Values.writer.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ff-proxy.writer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ff-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.writer.service.type }}
  ports:
    - port: {{ .Values.writer.service.port }}
      targetPort: sdk
      protocol: TCP
      name: sdk
  selector:
    {{- include "ff-proxy.writer.SelectorLabels" . | nindent 4 }}
{{- end }}