version: "3.9"
services:
  proxy:
    environment:
      - LOG_LEVEL=INFO
      - REDIS_ADDRESS=redis:6379
      - READ_REPLICA=false
      - AUTH_SECRET=foobar
      - PROXY_KEY=${PROXY_KEY}
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ${CONFIG_VOLUME:-./config:/config}
      - ./tests/e2e/certs:/certs
    ports:
      - "7000:7000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"