{{- if .Values.readReplica.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ff-proxy.readReplica.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ff-proxy.labels" . | nindent 4 }}
  {{- if or .Values.readReplica.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.readReplica.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.readReplica.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.readReplica.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.readReplica.service.port }}
      protocol: TCP
      name: sdk
  selector:
    {{- include "ff-proxy.readReplica.SelectorLabels" . | nindent 4 }}
    app: {{ include "ff-proxy.readReplica.name" . }}
{{- end }}