version: "3.9"
services:
  primary:
    image: "harness/ff-proxy:v2.0.0-rc.5"
    environment:
      - LOG_LEVEL=INFO
      - PROXY_KEY=<your proxy key>
      - REDIS_ADDRESS=redis:6379
      - READ_REPLICA=false
      - AUTH_SECRET=foobar
    ports:
      - "7001:7000"
    depends_on:
      - redis

  replica:
    image: "harness/ff-proxy:v2.0.0-rc.5"
    environment:
      - LOG_LEVEL=INFO
      - REDIS_ADDRESS=redis:6379
      - READ_REPLICA=true
      - AUTH_SECRET=foobar
    ports:
      - "7002:7000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  prometheus:
    image: "prom/prometheus:v2.47.2"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    logging:
      driver: none

  grafana:
    image: "grafana/grafana:10.2.0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    logging:
      driver: none

