version: "3.9"
services:
  primary:
    image: "harness/ff-proxy:dev-latest-v2"
    environment:
      - LOG_LEVEL=DEBUG
      - PROXY_KEY=<proxy key>
      - REDIS_ADDRESS=redis:6379
      - REDIS_USERNAME=your_username
      - REDIS_PASSWORD=your_password
      - READ_REPLICA=false
      - AUTH_SECRET=foobar
    ports:
      - "7001:7000"
    depends_on:
      - redis

  replica:
    image: "harness/ff-proxy:dev-latest-v2"
    environment:
      - LOG_LEVEL=INFO
      - REDIS_ADDRESS=redis:6379
      - REDIS_USERNAME=your_username
      - REDIS_PASSWORD=your_password
      - READ_REPLICA=true
      - AUTH_SECRET=foobar
    ports:
      - "7002:7000"
    depends_on:
      - redis

  redis:
    image: "redis:7.2.5"
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
